microservices:
  echo: "http://echo.apps.internal:8080/api/echo"
  time: "http://time.apps.internal:8080/api/time"
  greeting: "http://greeting.apps.internal:8080/api/greeting"
  whoami: "http://whoami.apps.internal:8080/api/whoami"
